In [2]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.tree import DecisionTreeClassifier

In [3]:
data = pd.read_csv('Churn_Modelling.csv')
data

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [4]:

X = data.iloc[: , 3:13].values
X1 = data.iloc[: , 3:13].values

y = data.iloc[:, 13].values
y1 = data.iloc[:, 13].values
X,y


(array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
        [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
        [502, 'France', 'Female', ..., 1, 0, 113931.57],
        ...,
        [709, 'France', 'Female', ..., 0, 1, 42085.58],
        [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
        [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object),
 array([1, 0, 1, ..., 1, 1, 0]))

In [5]:
X[:,2], X1[:,2]

(array(['Female', 'Female', 'Female', ..., 'Female', 'Male', 'Female'],
       dtype=object),
 array(['Female', 'Female', 'Female', ..., 'Female', 'Male', 'Female'],
       dtype=object))

In [6]:
lb = LabelEncoder()
X[:,2] = lb.fit_transform(X[:,2])
X[:,1] = lb.fit_transform(X[:,1])

X1[:,2] = lb.fit_transform(X1[:,2])
X1[:,1] = lb.fit_transform(X1[:,1])


In [7]:
from sklearn.compose import ColumnTransformer
#LabelRncoder = 
#OneHotEncoder 
ct = ColumnTransformer([("Country", OneHotEncoder(), [1])], remainder = 'passthrough')
X = ct.fit_transform(X)
X1 = ct.fit_transform(X1)
X 

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [8]:
#Multi-collinearity 
#n sub categories, you need n-1 categories

In [9]:
#X = pd.DataFrame(X, columns = ["X2", "X3", "Credit Score", "Gender", "Age","Tenure", "Balance", "NumofProducts", "HasCrCard", "IsActive Member", "Estimated Salary"])
X1 = pd.DataFrame(X1, columns = ["X1","X2", "X3", "Credit Score", "Gender", "Age","Tenure", "Balance", "NumofProducts", "HasCrCard", "IsActive Member", "Estimated Salary"])

X1

X1   X2   X3 Credit Score Gender Age Tenure    Balance NumofProducts  \
0     1.0  0.0  0.0          619      0  42      2        0.0             1   
1     0.0  0.0  1.0          608      0  41      1   83807.86             1   
2     1.0  0.0  0.0          502      0  42      8   159660.8             3   
3     1.0  0.0  0.0          699      0  39      1        0.0             2   
4     0.0  0.0  1.0          850      0  43      2  125510.82             1   
...   ...  ...  ...          ...    ...  ..    ...        ...           ...   
9995  1.0  0.0  0.0          771      1  39      5        0.0             2   
9996  1.0  0.0  0.0          516      1  35     10   57369.61             1   
9997  1.0  0.0  0.0          709      0  36      7        0.0             1   
9998  0.0  1.0  0.0          772      1  42      3   75075.31             2   
9999  1.0  0.0  0.0          792      0  28      4  130142.79             1   

     HasCrCard IsActive Member Estimated Salary  
0            1               1        101348.88  
1            0               1        112542.58  
2            1               0        113931.57  
3            0               0         93826.63  
4            1               1          79084.1  
...        ...             ...              ...  
9995         1               0         96270.64  
9996         1               1        101699.77  
9997         0               1         42085.58  
9998         1               0         92888.52  
9999         1               0         38190.78  

[10000 rows x 12 columns]

In [ ]:
X1 = X1.drop("X1", axis = 1)
X1
#Apple = 1- Bananas - Ornage

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
#Feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
%pip install statsmodels 


In [ ]:
import statsmodels.api as sm
X_train = sm.add_constant(X_train)
#add_constant add a column with 1 values
X_test = sm.add_constant(X_test)
classifier = sm.Logit(y_train, X_train) #Logit
model = classifier.fit()
model.summary()

In [ ]:
import seaborn as sns
from sklearn import metrics
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

y_pred = model.predict(X_test)
y_pred = (y_pred > 0.45) #
print("Accuracy", metrics.accuracy_score(y_test, y_pred))
cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt ='')

Decision Tree classifer

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
X_train1, X_test1, y_train1, y_test1 = train_test_split(X1, y1, test_size = 0.2, random_state = 0)

In [ ]:
#Feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train1 = sc.fit_transform(X_train1)
X_test1 = sc.transform(X_test1)

In [ ]:
clf  = DecisionTreeClassifier(max_depth = 6)
clf = clf.fit(X_train1, y_train1)
Y_pred = clf.predict(X_test1)

In [ ]:
print("Accuracy", metrics.accuracy_score(y_test1, Y_pred))

In [ ]:
new_customer = clf.predict(sc.transform(np.array([[0,0,1,600,1,40,3,60000,2,1,1,50000]])))
new_customer

In [ ]:
!pip install six

In [ ]:
from sklearn.tree import export_graphviz
from six import StringIO  
from IPython.display import Image  
import pydotplus
feature_cols = ["X1", "X2", "X3", "Credit Score", "Gender", "Age","Tenure", "Balance", "NumofProducts", "HasCrCard", "IsActive Member", "Estimated Salary"]
dot_data = StringIO()
export_graphviz(clf, out_file=dot_data,  
                filled=True, rounded=True,
                special_characters=True,feature_names = feature_cols,class_names=['0','1'])
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())  
graph.write_png('creditmodel.png')
Image(graph.create_png())